### ISSUE TITLE
ALL - Hover functionality not working optimally

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#11]
Cursor has to be just right in order for hover text to show up.  Is it possible to replace with Right Click pop up box or something like that which is a more definitive user action.

**Comment by WorkMAE** [comment]
Due to the way reports are handled inside Access, each row is actually a singleton object, so if I create a box for a row it will pop up on every row, which will slow things down and won't work right...I tried it prior to the solution I implemented now.  I know it isn't ideal but it's a limitation of reports in Access unfortunately.  I will see if there is any other solution to this when I get time down the road.
