### ISSUE TITLE
SAM (Clients View) - Clients Info Modal is blank

### ISSUE THREAD

**Issue by kartikbshukla** [WorkMAE/AMProject#54]
Nothing shows up when clicking on a client

![clients modal pic](https://user-images.githubusercontent.com/31935414/39832543-772a3e84-5395-11e8-9493-f4a42dcdb926.PNG)

**Comment by WorkMAE** [comment]
This is now resolved---it was attempting to use the SAM Name instead of SAMIndex...I had changed this a while back and forgot to update it in this section of code.  Fixed in DEV, will be released to PROD tonight.

![image](https://user-images.githubusercontent.com/31932842/39888242-3fbd0166-5462-11e8-88bb-32b6a2488335.png)
